name: Build and Push Docker image

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch
    paths:
      - 'Dockerfile.11.8.0-vc-ubuntu22.04-py3.11'  # Trigger only when Dockerfile.devel changes

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: 'Dockerfile.11.8.0-vc-ubuntu22.04-py3.11'
          push: true
          tags: saracenrhue/cuda-images:11.8.0-vc-ubuntu22.04-py3.11
          platforms: linux/amd64,linux/arm64
